esphome:
  name: "thermometer-bridge"

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EtBTyznIovYQJCXefAkHKlF+nYpPR3dapdvrvGWlFbc="

ota:
  password: "d30493a3babfa0300e130cb8a99d0376"

wifi:
  ssid: Zelei_Ext
  password: kutyafule

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Thermometer Fallback Hotspot"
    password: "arev9pZy4JKO"

captive_portal:

external_components:
  - source:
      type: local
      path: d:\Work\Esphome\q8rf\esphome-q8rf\components\


spi:
  clk_pin: D5
  miso_pin: D6
  mosi_pin: D7    

q8rf_zone_controller:
  id: Q8RFController
  cs_pin: D8

switch:
  - platform: q8rf_zone_controller
    name: study_heater_1
    q8rf_device_id: 0x6ed5
    q8rf_zone_id: 1

  - platform: q8rf_zone_controller
    name: study_heater_2
    q8rf_device_id: 0x6ed6
    q8rf_zone_id: 2

button:
  - platform: q8rf_zone_controller
    name: study_heater_1
    q8rf_device_id: 0x6ed5
    q8rf_zone_id: 1

  - platform: q8rf_zone_controller
    name: study_heater_2
    q8rf_device_id: 0x6ed6
    q8rf_zone_id: 2
      
