esphome:
  name: "thermometer-bridge"

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EtBTyznIovYQJCXefAkHKlF+nYpPR3dapdvrvGWlFbc="

ota:
  password: "d30493a3babfa0300e130cb8a99d0376"

wifi:
  ssid: Zelei_Ext
  password: kutyafule

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Thermometer Fallback Hotspot"
    password: "arev9pZy4JKO"

captive_portal:



spi:
  clk_pin: D5
  miso_pin: D6
  mosi_pin: D7  

external_components:
  - source: github://ZeleiAttila/esphome-q8rf@main
    components: [ q8rf_zone_controller ]
q8rf_zone_controller:
  id: Q8RFController
  cs_pin: D8

switch:
  - platform: q8rf_zone_controller
    name: controller_3_zone_3
    q8rf_device_id: 0x6ed5
    q8rf_zone_id: 3

  - platform: q8rf_zone_controller
    name: controller_3_zone_4
    q8rf_device_id: 0x6ed5
    q8rf_zone_id: 4

button:
  - platform: q8rf_zone_controller
    name: controller_3_zone_3
    q8rf_device_id: 0x6ed5
    q8rf_zone_id: 3

  - platform: q8rf_zone_controller
    name: controller_3_zone_4
    q8rf_device_id: 0x6ed5
    q8rf_zone_id: 4
      

  